services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/ecommerce
      JWT_SECRET: dev-secret-change-in-production
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin123456
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
  mailserver:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web interface port

  invoice-api:
    build:
      context: ./backend
      dockerfile: Dockerfile.invoice-api
    ports:
      - "8080:8080"
    environment:
      - SMTP_HOST=mailserver
    depends_on:
      - mailserver
    volumes:
      - ./backend:/app

volumes:
  postgres_data:
