services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/ecommerce
      JWT_SECRET: dev-secret-change-in-production
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin123456
      SALES_MANAGER_EMAIL: salesmanager@example.com
      SALES_MANAGER_PASSWORD: salesmanager123456
      SALES_MANAGER_NAME: Jane Smith
      PRODUCT_MANAGER_EMAIL: productmanager@example.com
      PRODUCT_MANAGER_PASSWORD: productmanager123456
      PRODUCT_MANAGER_NAME: John Doe
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
  mailserver:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web interface port

  invoice-api:
    build:
      context: ./backend
      dockerfile: Dockerfile.invoice-api
    ports:
      - "8080:8080"
    environment:
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      # This Gmail account is provided for the entire project and all group members.
      # The provider of this account is not responsible for any actions taken by 
      # group members using these credentials.
      - SMTP_USER=invoice.fier@gmail.com
      - SMTP_PASS=zyis qnxu djvz mdws
      - SENDER_EMAIL=invoice.fier@gmail.com
    volumes:
      - ./backend:/app

volumes:
  postgres_data:
