name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-format:
    name: Lint & Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          cache: "npm"
          cache-dependency-path: |
            frontend/package-lock.json
            backend/package-lock.json

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Frontend ESLint
        run: npm run lint
        working-directory: frontend

      - name: Frontend Prettier
        run: npm run format:check
        working-directory: frontend

      - name: Install backend dependencies
        run: npm ci
        working-directory: backend

      - name: Backend ESLint
        run: npm run lint
        working-directory: backend

      - name: Backend Prettier
        run: npm run format:check
        working-directory: backend

  test:
    name: Test
    runs-on: ubuntu-latest

    env:
      JWT_SECRET: test-secret

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          cache: "npm"
          cache-dependency-path: |
            frontend/package-lock.json
            backend/package-lock.json

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Frontend Tests
        run: npm test
        working-directory: frontend

      - name: Install backend dependencies
        run: npm ci
        working-directory: backend

      - name: Backend Tests
        run: npm test
        working-directory: backend

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Frontend build
        run: npm run build
        working-directory: frontend
